### ISSUE TITLE
Generate new cfg

### ISSUE THREAD

**Issue by Ic3dM4n** [srcdslab/sm-plugin-BossHP#4]
Amazing and simple life counter
https://prnt.sc/2Zvk5zPjfGrx

1.Where do I get or how do I make the cfg of the maps that have bosses?
2.Can the text be made bigger?
3.Is it possible to put different colors? ex: {green}BOSS: {red}HP

**Comment by maxime1907** [comment]
this plugin is the base to interact with bosses, its mainly like an api

these functions you are talking about are integrated in this plugin:
- https://github.com/srcdslab/sm-plugin-BossHUD
